title: Anuradha Kumari
headline: test headline
description: >
  Tech Enthusiast | Web Developer | Learner | Trainer | Blogger | Speaker
theme: jekyll-theme-cayman
plugins:
  - jemoji
twitter_url: https://twitter.com/miracle_404
linkedin_url:	https://www.linkedin.com/in/anuradha15/
stackoverflow_url: https://stackoverflow.com/users/11406789/anuradha-kumari
hackerrank_url: https://www.hackerrank.com/anuradhak79
numOfBlogs: 12
github: >
  repository_url: https://github.com/anuk79/anuk79.github.io
  repository_name: This portfolio
  owner_url: https://anuk79.netlify.app/
  owner_name: Anuradha Kumari
